export default {
    varyBigTitle: 45,
    bigTitle: 40,
    title: 35, 
    subtitle: 28,
    subsubtitle: 24,
    subsubsubtitle: 22,
    bigContent: 24,
    button: 24,
    content: 24, 
    smallContent: 18,
    varySmallContent: 14,
    veryvarySmallContent: 12,
    tinyContent: 10,
    iconInSmallButton: 20,
    iconInMediumButton: 80,
    smallButton: 16,
}