name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck-and-lint:
    name: TypeScript and ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check
